In [1]:
# Numpy package is mostly used for numerical & scientific computations.

# Numpy has internally build list & dictionaries so we can perform mathematical computations easily.

# Numpy provide extension for multidimensional arrays through lists.(1D array is like vector, 2D array is like matrix, 3D array is like cube where data is stored in each cell of cube)

# Numpy provides array oriented computation.


In [1]:
# Creating array using array() function

import numpy as np      # package import with alias name "np"

a=np.array([1,2,3,4])    # array() function used to create array by passing list 

print("Numpy Array is ",a)


Numpy Array is  [1 2 3 4]


In [7]:
# Creating array using arange() function

print("Numpy array is ",np.arange(11))    # create array ranges between 0 to 10


Numpy array is  [ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
# Python list - takes more time 

l=range(1000)

%timeit [i**2 for i in l]    # measures how much time it took per iteration


235 µs ± 1.65 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
# Python numpy - 

a=np.arange(1000)

%timeit a**2


913 ns ± 7.21 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
# Creatig one dimensional array - also called as vector

a=np.array([1,2,3,4])

a     # print array

a.ndim      # print dimension of array

a.shape    # print shape or size of array

len(a)     # shows how many elements are there in array


4

In [26]:
# Creating two dimensional array - also called as matrix

ta=np.array([[1,2,3],[4,5,6]])   # pass elements thorugh list within list

ta

ta.ndim       # print dimensions

ta.shape      # print rows & columns of array i.e. 2 row,3 column

len(ta)       # In 2D/3D len() returns size of first dimension i.e. row


2

In [30]:
# Creating three dimensional array - also called as tensor

tha=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

tha

tha.ndim     # print dimensions

tha.shape    # print length,breadth,depth of array

len(tha)     # In 2D/3D len() returns size of first dimension i.e. row


2

In [32]:
# Function for creating arrays -

# 1. arange() - It's an array valued version of built-in range() function.

q=np.arange(10)

q


# arange() with step size i.e. - arange(start_value,end_value,step_size) "here end value is exclusive means less then"

z=np.arange(1,10,2)     # print array of odd number

z


array([1, 3, 5, 7, 9])

In [10]:
# 2. linspace() - means linear space,used for breaking-up the region into equal space

x=np.linspace(0,1,6)   # linspace(start,end,no.of points), region starts from 0 & ends 1 so it divide this into 6 equal parts

x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [12]:
# 3. ones() - create array of value "one",but pass value through tuple

o=np.ones((2,2))

o


array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# 4. zeros() - create array of value "zero",but pass value through tuple

w=np.zeros((3,3))

w


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# 5. eye() - create identity matrix whose diagonal (i.e. top left to bottom right) elements are 1

I=np.eye(3)

I

i=np.eye(2)

i

array([[1., 0.],
       [0., 1.]])

In [21]:
# 6. diag() - create diagonal matrix whose diagonal elements are defined by user.

d=np.diag((1,2,3,4))

d

np.diag(d)    # extract diagonal element only


array([1, 2, 3, 4])

In [23]:
# 7. rand() - It's available in "random" module of numpy package, which create array through random values

r=np.random.rand(3)

r     # It prints uniform distributed random number


R=np.random.randn(3)     # randn stands for random normal

R      # It prints standard normal variant number / gausion distributed 


array([-0.07240304,  1.63999608, -1.2948085 ])

In [3]:
# Numpy basic Data-Type

# a) dtype - prints for datatype of variable.

g=np.arange(1,6)

g.dtype


# you can explicitly specify data type which you want using "dtype" parameter to arange() function.

G=np.arange(11,dtype='float64')

G

# for zeros() & ones() the default data type is float.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
# b) complex - 

c=np.array([1+2j,2+4j])

c.dtype

dtype('complex128')

In [8]:
# c) boolean - 

b=np.array([True,False,False,True])

b.dtype

dtype('bool')

In [10]:
# d) string - 

s= np.array(['abc','def','ghi','jkl'])

s.dtype

dtype('<U3')

In [19]:
# Indexing & Slicing -

# A) Indexing -

idx=np.arange(10)

print(idx)

idx[2]     # element access using perticular index from 1-D array


[0 1 2 3 4 5 6 7 8 9]


2

In [22]:
# for multidimensional array,indexes are tuple of integers.

dig=np.diag([1,2,3])

dig[1,1]    


2

In [23]:
# Assigning value to array

dig[2,1]=5

dig

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [24]:
# B) Slicing - 

sl=np.arange(10)

sl[1:10:2]     # ":" used for slicing


array([1, 3, 5, 7, 9])

In [26]:
# combine assignment & slicing

sa=np.arange(10)

sa[5:]=10     # slicing starts onwards 5 till end & value assign is 10

sa


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [28]:
sa1=np.arange(5)

sa[5:]=sa1[::-1]

sa

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [2]:
# Copies & Views - slicing operation create a view on array so the original array is not copied on memory, its just a way of accessing array data.

# * view - when we modify a view, the original array gets modified too.

t=np.arange(10)

t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
v=t[::2]     # through slicing view created

v     # "v" is sub-array of "t"

array([0, 2, 4, 6, 8])

In [4]:
np.shares_memory(t,v)    # used to check memory is shareable or not

True

In [5]:
print(id(t))

print(id(v))

# although there address is different

140469471618352
140469475527536


In [4]:

np.may_share_memory(t,v)    # used to check if two array shares same memory block


True

In [5]:
# modifing element of sub array

v[0]=10     

v

array([10,  2,  4,  6,  8])

In [6]:
# even we modify 2nd array,it update 1st array because they share same memory

t           # main array gets modified too

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [7]:
# * copy - use copy() to force copy

i=np.arange(11)

i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# creating sub-array 

j=i[::3].copy()

j

array([0, 3, 6, 9])

In [11]:
np.may_share_memory(i,j)    # because i & j points to different locations

False

In [12]:
# modifing j

j[0]=11

j

array([11,  3,  6,  9])

In [13]:
i    # copy will not affect the original array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Numpy arrays can be indexed with slices also with boolean,integers too called "masks" ,this method is called as fancy indexing.

# fancy indexing i.e. mask creates copies not views.

# 1. boolean mask - 

fi=np.random.randint(0,20,15)     # another way of creating random numbers, syntax(start,end,no_count)

fi     # prints array having 15 numbers only ranges from 0 to 20 randomly


array([ 9, 13, 12,  2, 11,  3,  4, 14, 19, 19,  2,  7, 12, 17, 11])

In [15]:
mask=(fi%2==0)     # boolean expression assigned

read_fi=fi[mask]    # evaluate mask

read_fi

array([12,  2,  4, 14,  2, 12])

In [16]:
# 2. indexing with mask can be useful to assign new value for sub-array

fi[mask]=-1     # all even numbers became equals to -1

fi

array([ 9, 13, -1, -1, 11,  3, -1, -1, 19, 19, -1,  7, -1, 17, 11])

In [20]:
# 3. indexing with an array of integers

k=np.arange(0,100,10)      # (strat,end,step_size)

k


array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
# perticular array elements accessed using index

k[[2,6,9,3,2]]   # pass list within list


array([20, 60, 90, 30, 20])

In [24]:
# value changed of array element using index

k[[0,9]]=1   # It take list within list

k

array([ 1, 10, 20, 30, 40, 50, 60, 70, 80,  1])