In [1]:
import numpy as np

In [7]:
# Numpy Operations -

# 1. Scalar addition & multiplication (done elementwise)

sa=np.array([77,43,31])

print("Array is ",sa) 

print("Scalar addition is ",sa+1)    # adds 1 to each element of array

print("Scalar multiplication is ",sa**2)     # multiply each element by 2 


Array is  [77 43 31]
Scalar addition is  [78 44 32]
Scalar multiplication is  [5929 1849  961]


In [4]:
sa=np.array([1,2,3,4])

sb=np.ones(4)+1     # create array of 1 then add 1 to each element

print("Another array is ",sb)

print("Substraction of sa & sb is ",sa-sb)

print("Multiplication is ",sa*sb)


Another array is  [2. 2. 2. 2.]
Substraction of sa & sb is  [-1.  0.  1.  2.]
Multiplication is  [2. 4. 6. 8.]


In [6]:
# 2. Matrix multiplication -

m=np.diag([1,2,3,4])

print(m)

print("-------------------------")

print("Matrix multiplication is ")

print(m*m)     # it will do elementwise multiplication 

print("-------------------------")

print(m.dot(m))    # it will do matrix multiplication

print("***** Another Example *****")

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Elementwise multiplication is ")

print(a*a)    # it will do elementwise multiplication 

print("Matrix multiplication is ")

print(a.dot(a))    # it will do matrix multiplication


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
-------------------------
Matrix multiplication is 
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
-------------------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***** Another Example *****
Elementwise multiplication is 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Matrix multiplication is 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [52]:
# 3. Comparison - 

c1=np.array([1,2,3,4])

c2=np.array([5,2,2,4])

print("equal or not ",c1==c2)    # elementwise comparison is done

print("Greater or not ",c1>c2) 

print("***************---------------***************")

c3=np.array([1,2,3,4])

print("Array c1 equal to c2 ",np.array_equal(c1,c2))      # arraywise comparison is done

print("Array c1 equal to c3 ",np.array_equal(c1,c3))

print("***************---------------***************")

la=np.array([1,1,0,0])

lb=np.array([1,0,1,0])

print("Logical or ",np.logical_or(la,lb))      # logical operation

print("Logical and ",np.logical_and(la,lb))

print("***************---------------***************")

print("All function results ",np.all([True,True,False]))     # any one element is false return false else true like logical and

print("Any function results ",np.any([True,False,False]))    # any one element is true return true else false like logical or

z=np.zeros((50,50))

print("Result is ",np.any(z!=0))      # used for array comparison

print("Result is ",np.all(z==z))



equal or not  [False  True False  True]
Greater or not  [False False  True False]
***************---------------***************
Array c1 equal to c2  False
Array c1 equal to c3  True
***************---------------***************
Logical or  [ True  True  True False]
Logical and  [ True False False False]
***************---------------***************
All function results  False
Any function results  True
Result is  False
Result is  True


In [27]:
# 4. Trigonometric functions -

ta=np.arange(5)

print("array is ",ta)

print("sin of a is ",np.sin(ta))

print("log of a is ",np.log(ta))

print("exponent of a is ",np.exp(ta))


array is  [0 1 2 3 4]
sin of a is  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
log of a is  [      -inf 0.         0.69314718 1.09861229 1.38629436]
exponent of a is  [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


<ipython-input-27-487d40ca5847>:9: RuntimeWarning: divide by zero encountered in log
  print("log of a is ",np.log(ta))


In [44]:
# 5. Basic Reduction Functions - 

# a) sum() -

ra=np.array([10,9,8,7,6])

print("Sum of array is",sum(ra))

print("***************---------------***************")


# b) sum by columns & rows -

ca=np.array([[1,1],[2,2]])

print(ca)

print("Column-wise addition is ",ca.sum(axis=0))     # "axis=0" will perform columnwise sum

print("row-wise addition is ",ca.sum(axis=1))        # "axis=1" will perform rowwise sum

print("***************---------------***************")


# c) min & max -

mn=np.array([4,5,6,7,8])

print("Minimum number of array is ",mn.min())

print("Maximum number of array is ",mn.max())

print("***************---------------***************")

print("index of minimum number is ",mn.argmin())       # argmin() returns index of minimum number

print("index of maximum number is ",mn.argmax())       # argmax() returns index of maximum number

print("***************---------------***************")


Sum of array is 40
***************---------------***************
[[1 1]
 [2 2]]
Column-wise addition is  [3 3]
row-wise addition is  [2 4]
***************---------------***************
Minimum number of array is  4
Maximum number of array is  8
***************---------------***************
index of minimum number is  0
index of maximum number is  4
***************---------------***************


In [3]:
# 6. Loading text file into numpy object "np" 

data=np.loadtxt('file_name')

data        # print data in array format

data.T      # transpose of matrix done 



In [6]:
# 7. Element-wise Broadcasting - means creating tiles of array to perform operations

ba=np.arange(0,40,10)

print("Original array is ",ba)

print("_______________________________________")

ba1=np.tile(np.arange(0,40,10),(3,1))      # tile() create copies of array
 
print("Broadcasting array is ")

print(ba1)

print("_______________________________________")

ba1=ba1.T      # "T" it's a module defined in numpy package used for transpose of matrix 

print("Transpose of matrix ")

print(ba1)

print("_______________________________________")

ba2=np.array([0,1,2])

print("Another array is ",ba2)

print("_______________________________________")

ba1+ba2

Original array is  [ 0 10 20 30]
_______________________________________
Broadcasting array is 
[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
_______________________________________
Transpose of matrix 
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
_______________________________________
Another array is  [0 1 2]
_______________________________________


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [35]:
# 8. Matrix-wise Broadcasting - 

# np.newaxis object allows us to add an axis to an array

# newaxis is used to increase the dimension of existing array by one more dimension hence 1D became 2D, 2D became 3D and so on.

a=np.arange(0,40,10)   

print("First Array dimension is",a.shape)     # shape defines dimensions of array

print("First Array is ",a)       # creates 1D array

print("_______________________________________")

a1=a[:,np.newaxis]        # convert 1D array to 2D array (i.e. adds new axis to form 2D array) ,Here ":" indicates all rows of array

print("New array dimension is",a1.shape)    #  checks whether axis is added or not

print(a1)      # creates 2D array

print("_______________________________________")

b=np.array([0,1,2])

print("Second Array dimension is",b.shape)

print("Second array is ")

print(b)

print("_______________________________________")

print("Addition of two array is ")

print(a1+b)


Array dimension is (4,)
First Array is  [ 0 10 20 30]
_______________________________________
New array dimension is (4, 1)
[[ 0]
 [10]
 [20]
 [30]]
_______________________________________
Second Array dimension is (3,)
Second array is 
[0 1 2]
_______________________________________
Addition of two array is 
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [58]:
# 9. Array shape manipulation 

# A) Flattening -

fl=np.array([[1,2,3],[4,5,6]])

print("Array is ")

print(fl)

print("-------------------------------")

print("Flattened array is ",fl.ravel())    # ravel() converts 2D array into 1D

print("-------------------------------")

print("Transpose of flattened array is ")

print(fl.T)                 

print("-------------------------------")

print("Ravel after transpose ",fl.T.ravel())      # used to get array with different values


Array is 
[[1 2 3]
 [4 5 6]]
-------------------------------
Flattened array is  [1 2 3 4 5 6]
-------------------------------
Transpose of flattened array is 
[[1 4]
 [2 5]
 [3 6]]
-------------------------------
Ravel after transpose  [1 4 2 5 3 6]


In [57]:
# B) Reshaping - It's nothing but inverse of flattening

print("Dimension of original array is ",fl.shape)

print("-------------------------------")

r=fl.ravel()          # convert simple array to flattened array

print("Raveled array is ",r)

print("-------------------------------")

r=r.reshape(2,3)      # convert flattened array to simple array,also return copy of array sometime

print("Array after reshaping ")

print(r)

Dimension of original array is  (2, 3)
-------------------------------
Raveled array is  [1 2 3 4 5 6]
-------------------------------
Array after reshaping 
[[1 2 3]
 [4 5 6]]


In [5]:
# C) Dimension shuffling - 

ds=np.arange(4*3*2).reshape(4,3,2)    # it will create 3D array having 4 matrix,3 rows & 2 columns ; values ranges from 0 to 23

print("Array is ")

ds

ds[0,2,1]      # change value of 0th array,2nd row 1st column 

print("Changed value array ",ds)


Array is 
Changed value array  [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [21]:
# D) Sorting Data -

# sorting using axis :

s=np.array([[7,6,5],[10,9,8]])

print("Array before sorting ")

print(s)

print("Array after sorting ")

s.sort(axis=1)        

print(s)

print("-----------------------------------")

# sorting using fancy indexing :

sf=np.array([8,7,6,5,4])

s=np.argsort(sf)     # argsort() returns index after sorting element

print("sorted index are ",s)      

print("fetching element through index is ",sf[s])     # sf[s] used to get element through sorted index


Array before sorting 
[[ 7  6  5]
 [10  9  8]]
Array after sorting 
[[ 5  6  7]
 [ 8  9 10]]
-----------------------------------
sorted index are  [4 3 2 1 0]
fetching element through index is  [4 5 6 7 8]
